Feature/added components and redux store
codingAngarita/react-bookstore pull request #2
Opened 2020-08-18 20:26 UTC by codingAngarita

# Hi :robot: 

This is the pull request for the milestone 2 of the Bookstore project.

### Introduced features:
* Added book reducers.
* Added book actions `createBook` and `removeBook`.
* Added `Book` container.
* Added `BookList` and `BookForm` component.

2020-08-18 22:45 UTC, shloch requested changes
## Hello @codingAngarita , 

You really did a good job with coding of the core modules

We however just have small organisational issues, that's all (see below)

![Screen Shot 2020-08-18 at 11 30 15 PM](https://user-images.githubusercontent.com/40712459/90572114-2be05200-e1ab-11ea-9285-99acbb7fb918.png)

from instructions we have 
- 2 `presentational` components (`App` and `Book`) : they should be in the folder `src/components`
- 02 `container` components (`BooksList` and `BooksForm`) : they should be in the folder `src/containers`

So let's just polish this little detail

Happy coding

2020-08-18 22:45 UTC, shloch commented on src/index.js
>  );
- You needed to add initial/sample books here [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/InitialBooks.png)]

2020-08-18 22:45 UTC, shloch commented on src/containers/Book.js
> +
- this component should be inside the folder `src/components`

2020-08-18 22:45 UTC, shloch commented on src/components/BooksList.js
> +import { connect } from 'react-redux';
- relocate component to folder `src/containers`

2020-08-18 22:45 UTC, shloch commented on src/components/BooksForm.js
> +
- relocate to folder `src/containers`

2020-08-19 03:53 UTC, codingAngarita commented
# Hi! :robot: 
Thanks for the feedback on the organisational problems.

### Introduced changes:
* Moved `BooksForm` and `BooksList` to to the `containers` folder.
* Moved `Book` to the `components` folder.

@codingAngarita :wave:

2020-08-19 07:43 UTC, bellom approved these changes
## Hi @codingAngarita :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-20 23:22 UTC, merged