Feature/added filter by category
codingAngarita/react-bookstore pull request #4
Opened 2020-08-19 19:36 UTC by codingAngarita

# Hi! :rocket: 

This it the pull request for the milestone #4 of the Bookstore project.

## You can check a live version of this pull request [here.](https://ca-react-bookstore.herokuapp.com/)
### Added features:
* `filter` reducer.
* `CHANGE_FILTER` action.
* `CategoryFilter` component.
* Filtered books using current filter category.

@codingAngarita :wave:

2020-08-20 07:07 UTC, bellom requested changes
## Hi @codingAngarita  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-20 07:07 UTC, bellom commented on src/actions/reducers/book.js
> +export const generateId = () => Math.floor(Math.random() * (99999 - 10000) + 10000);
**[Optional]**
Kindly be aware that you can use uuidv4 to automatically generate ids. read more 👉 https://www.npmjs.com/package/uuidv4

2020-08-20 07:07 UTC, bellom commented on src/components/Book.js
> +  const { removeBook } = props;
We can simply do this in one line;
`const { id, title, .... } = props`

2020-08-20 07:07 UTC, bellom commented on src/containers/BooksList.js
> +  const { currentFilter } = props;
Let's do this in one line 👍

2020-08-20 07:07 UTC, bellom commented on src/containers/BooksForm.js
> +      </div>
Let's validate our form so that users can't create an empty book.

2020-08-20 23:13 UTC, codingAngarita commented
# Hi! :robot: 

### New changes:
* Added `uuid` package to manage book ids.
* Used one line prop destructure
* Added empty book title validation before saving

2020-08-21 08:28 UTC, bellom approved these changes
## Hi @codingAngarita  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-21 15:43 UTC, merged